version: "3"

volumes: # 自定义数据卷，位于宿主机/var/lib/docker/volumes内
 myproject_db_vol: # 定义数据卷同步容器内mysql数据
 myproject_redis_vol: # 定义数据卷同步redis容器内数据
 myproject_media_vol: # 定义数据卷同步media文件夹数据
 certs:
 vhost:
 html:
 dhparam:

services:
 redis:
   image: redis:5
   command: redis-server /etc/redis/redis.conf # 容器启动后启动redis服务器
   volumes:
      - myproject_redis_vol:/data # 通过挂载给redis数据备份
      - ./compose/redis/redis.conf:/etc/redis/redis.conf # 挂载redis配置文件
   ports:
      - "6379:6379"
   restart: always # always表容器运行发生错误时一直重启

 db:
   image: mysql:5.7
   environment:
      - MYSQL_ROOT_PASSWORD=db_password # 数据库密码
   volumes:
      - myproject_db_vol:/var/lib/mysql:rw # 挂载数据库数据, 可读可写
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf # 挂载配置文件
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # 挂载数据初始化sql脚本
   ports:
      - "3306:3306" # 与配置文件保持一致
   restart: always

 web:
   build: ./mmm957 # 使用myproject目录下的Dockerfile
   expose:
      - "8000"
   volumes:
      - ./mmm957:/var/www/html/mmm957 # 挂载项目代码
      - myproject_media_vol:/var/www/html/mmm957/media # 以数据卷挂载容器内用户上传媒体文件
      - ./compose/uwsgi:/tmp # 挂载uwsgi日志
   links:
      - db
      - redis
   depends_on: # 依赖关系
      - db
      - redis
   environment:
      - DEBUG=False
   restart: always
   tty: true
   stdin_open: true

 nginx-proxy:
   image: jwilder/nginx-proxy:alpine
   restart: always
   container_name: nginx-proxy
   ports:
      - "80:80"
      - "443:443"
   volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro

 nginx-proxy-letsencrypt:
   image: jrcs/letsencrypt-nginx-proxy-companion
   restart: always
   depends_on:
      - "nginx-proxy"
   volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
   environment:
#     - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=your_mail@gmail.com

 nginx:
   build: ./compose/nginx
   volumes:
      - ./mmm957/static:/usr/share/nginx/html/static # 挂载静态文件
      - ./compose/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      - ./compose/nginx/log:/var/log/nginx # 挂载日志
      - myproject_media_vol:/usr/share/nginx/html/media # 挂载用户上传媒体文件
   links:
      - web
   depends_on:
      - web
   restart: always
   environment:
      - VIRTUAL_HOST=957tw.com,www.957tw.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=957tw.com,www.957tw.com
      - LETSENCRYPT_EMAIL=your_mail@gmail.com
