# Generated by Django 3.1 on 2020-08-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('checking_code', models.CharField(default=0, max_length=6)),
                ('checking_times', models.IntegerField(default=0)),
                ('checking_error', models.IntegerField(default=0)),
                ('is_borrower', models.BooleanField(default=False)),
                ('is_lender', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='temp_Borrower',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan.temp_user')),
                ('nickname', models.CharField(default='先生/小姐', max_length=16)),
                ('line_id', models.CharField(max_length=16, null=True)),
                ('job', models.CharField(choices=[('農、林、漁、牧業', '農、林、漁、牧業'), ('勞工上班族', '勞工上班族'), ('交通運輸業', '交通運輸業'), ('餐旅服務業', '餐旅服務業'), ('公家機關', '公家機關'), ('建築業', '建築業'), ('娛樂業', '娛樂業'), ('大學生', '大學生'), ('其他', '其他'), ('無', '無')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_Lender',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan.temp_user')),
                ('nickname', models.CharField(max_length=16)),
                ('line_id', models.CharField(max_length=16, null=True)),
                ('region', models.CharField(choices=[('北、北、基（含宜蘭）', '北、北、基（含宜蘭）'), ('桃、竹、苗', '桃、竹、苗'), ('中、彰、投', '中、彰、投'), ('雲、嘉、南', '雲、嘉、南'), ('高雄、屏東', '高雄、屏東'), ('花蓮、台東', '花蓮、台東')], max_length=10, null=True)),
                ('highest_lending', models.IntegerField(null=True)),
                ('lending_way', models.CharField(choices=[('本票', '本票'), ('機車', '機車'), ('汽車', '汽車'), ('電話諮詢', '電話諮詢')], max_length=16, null=True)),
                ('lending_title', models.CharField(max_length=20, null=True)),
                ('lending_content', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_Borrowing_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('borrowing_way', models.CharField(choices=[('本票', '本票'), ('機車', '機車'), ('汽車', '汽車'), ('電話諮詢', '電話諮詢')], default='本票', max_length=16, null=True)),
                ('region', models.CharField(choices=[('基隆', '基隆'), ('台北', '台北'), ('新北', '新北'), ('桃園', '桃園'), ('新竹', '新竹'), ('苗栗', '苗栗'), ('台中', '台中'), ('彰化', '彰化'), ('南投', '南投'), ('雲林', '雲林'), ('嘉義', '嘉義'), ('台南', '台南'), ('高雄', '高雄'), ('屏東', '屏東'), ('宜蘭', '宜蘭'), ('花蓮', '花蓮'), ('台東', '台東')], max_length=2)),
                ('money_usage', models.CharField(max_length=16)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.temp_borrower')),
            ],
        ),
    ]
