# Generated by Django 3.1 on 2020-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_temp_borrower_temp_borrowing_message_temp_lender_temp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='lending_content',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lending_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
