# Generated by Django 3.1 on 2020-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200812_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000')], max_length=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='paying_month',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000')], max_length=10),
        ),
    ]
