# Generated by Django 3.1 on 2020-08-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20200812_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_borrowing_message',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='temp_lender',
            name='user',
        ),
        migrations.AddField(
            model_name='paying',
            name='ad_region',
            field=models.CharField(choices=[('北、北、基（含宜蘭）', '北、北、基（含宜蘭）'), ('桃、竹、苗', '桃、竹、苗'), ('中、彰、投', '中、彰、投'), ('雲、嘉、南', '雲、嘉、南'), ('高雄、屏東', '高雄、屏東'), ('花蓮、台東', '花蓮、台東')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paying',
            name='ad_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='line_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='region',
            field=models.CharField(choices=[('北、北、基（含宜蘭）', '北、北、基（含宜蘭）'), ('桃、竹、苗', '桃、竹、苗'), ('中、彰、投', '中、彰、投'), ('雲、嘉、南', '雲、嘉、南'), ('高雄、屏東', '高雄、屏東'), ('花蓮、台東', '花蓮、台東')], max_length=10),
        ),
        migrations.AlterField(
            model_name='borrowing_message',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.borrower'),
        ),
        migrations.AlterField(
            model_name='borrowing_message',
            name='borrowing_way',
            field=models.CharField(choices=[('本票', '本票'), ('機車', '機車'), ('汽車', '汽車'), ('電話諮詢', '電話諮詢')], default='本票', max_length=16),
        ),
        migrations.AlterField(
            model_name='borrowing_message',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='highest_lending',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lending_content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lending_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lending_way',
            field=models.CharField(choices=[('本票', '本票'), ('機車', '機車'), ('汽車', '汽車'), ('電話諮詢', '電話諮詢')], max_length=16),
        ),
        migrations.AlterField(
            model_name='lender',
            name='region',
            field=models.CharField(choices=[('北、北、基（含宜蘭）', '北、北、基（含宜蘭）'), ('桃、竹、苗', '桃、竹、苗'), ('中、彰、投', '中、彰、投'), ('雲、嘉、南', '雲、嘉、南'), ('高雄、屏東', '高雄、屏東'), ('花蓮、台東', '花蓮、台東')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lender',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='get_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paying',
            name='package',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='paying_month',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10),
        ),
        migrations.DeleteModel(
            name='temp_Borrower',
        ),
        migrations.DeleteModel(
            name='temp_Borrowing_Message',
        ),
        migrations.DeleteModel(
            name='temp_Lender',
        ),
        migrations.DeleteModel(
            name='temp_User',
        ),
    ]
