# Generated by Django 3.1 on 2020-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200812_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='paying',
            name='paying_month_ad',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paying',
            name='paying_month_lender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='region',
            field=models.CharField(choices=[('北、北、基（含宜蘭）', '北、北、基（含宜蘭）'), ('桃、竹、苗', '桃、竹、苗'), ('中、彰、投', '中、彰、投'), ('雲、嘉、南', '雲、嘉、南'), ('高雄、屏東', '高雄、屏東'), ('花蓮、台東', '花蓮、台東')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='receivable_money',
            field=models.IntegerField(null=True),
        ),
    ]
