# Generated by Django 3.1 on 2020-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20200816_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
