# Generated by Django 3.1 on 2020-08-19 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20200817_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ad_contact',
            name='paying_month',
        ),
        migrations.RemoveField(
            model_name='paying',
            name='paying_month_ad',
        ),
        migrations.AddField(
            model_name='ad_contact',
            name='paying_month_local',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ad_contact',
            name='paying_month_nation',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paying',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paying',
            name='paying_month_ad_local',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paying',
            name='paying_month_ad_nation',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_photo',
            field=models.ImageField(upload_to='%Y/%m'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='lender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan.lender'),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.employee'),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_lender',
            field=models.CharField(choices=[('月繳 20,000', '月繳 20,000'), ('季繳 54,000', '季繳 54,000'), ('年繳 108,000', '年繳 108,000'), ('月繳 12,000', '月繳 12,000'), ('季繳 30,600', '季繳 30,600'), ('年繳 100,800', '年繳 100,800'), ('月繳 30,000', '月繳 30,000'), ('季繳 76,500', '季繳 76,500'), ('年繳 252,000', '年繳 252,000')], max_length=10, null=True),
        ),
    ]
