# Generated by Django 3.1 on 2020-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20200820_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month_local',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month_nation',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_ad_local',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_ad_nation',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_lender',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='paying_month',
            field=models.CharField(choices=[('20,000', '20,000'), ('54,000', '54,000'), ('108,000', '108,000'), ('12,000', '12,000'), ('30,600', '30,600'), ('100,800', '100,800'), ('30,000', '30,000'), ('76,500', '76,500'), ('252,000', '252,000')], max_length=10),
        ),
    ]
