# Generated by Django 3.1 on 2020-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20200820_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month_local',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_contact',
            name='paying_month_nation',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_ad_local',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_ad_nation',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paying',
            name='paying_month_lender',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='paying_month',
            field=models.CharField(choices=[('20000', '20000'), ('54000', '54000'), ('108000', '108000'), ('12000', '12000'), ('30600', '30600'), ('100800', '100800'), ('30000', '30000'), ('76500', '76500'), ('252000', '252000')], max_length=10),
        ),
    ]
