# Generated by Django 3.1 on 2020-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20200821_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_photo',
            field=models.ImageField(upload_to='%Y/%m/'),
        ),
    ]
