# Generated by Django 3.1 on 2020-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20200824_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_photo',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_photo_big',
            field=models.ImageField(null=True, upload_to='%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_photo_small',
            field=models.ImageField(null=True, upload_to='%Y/%m/'),
        ),
    ]
